/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.distributor;

import database.Distributor_Manager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.manager.UI_DesignFunctions;
import ui.manager.UI_Manager;

/**
 *
 * @author deepthiramesh
 */
public class DistributorManagerJPanel extends javax.swing.JPanel {
    int distributorId;
    String username;
    int transporterId;
    
    int selectedOrderId ;
    /**
     * Creates new form DistributorManagerJPanel
     */
    public DistributorManagerJPanel(String username, int distributorId) {
        initComponents();
        this.distributorId = distributorId;
        this.username = username;
        System.out.println(username);
        System.out.println(distributorId);
        lblDistributorAdmin.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        AdminLabel = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblDistributorAdmin = new javax.swing.JLabel();
        lblDistributorAdmin1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ViewOrdersPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderOverview = new javax.swing.JTable();
        lblManufac = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        lblSts = new javax.swing.JLabel();
        btnAssignTransportNow = new javax.swing.JButton();
        TransportManagementPanel = new javax.swing.JPanel();
        btnOrderrOverview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderrOverview = new javax.swing.JTable();
        btnTransportationOverview = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransportation = new javax.swing.JTable();
        btnAssignTransport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ShipmentOverviewPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        StockOverviewPane = new javax.swing.JPanel();
        txtSearchh = new javax.swing.JTextField();
        btnTrackShipment = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTrackShipment = new javax.swing.JTable();
        btnBackk = new javax.swing.JButton();
        ManageStocksPane = new javax.swing.JPanel();
        txtManageSearch = new javax.swing.JTextField();
        btnMedicationOverview = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtCostPrice = new javax.swing.JTextField();
        txtSellingPrice = new javax.swing.JTextField();
        btnAddInventory = new javax.swing.JButton();
        btnUpdateInventory = new javax.swing.JButton();
        btnDeleteInventory = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMedicationOverview = new javax.swing.JTable();
        btnViewStock = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblViewStock = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(137, 87, 55));

        TopPanel.setBackground(new java.awt.Color(137, 87, 55));

        AdminLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(243, 233, 220));
        AdminLabel.setText("WELCOME");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblDistributorAdmin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblDistributorAdmin.setForeground(new java.awt.Color(243, 233, 220));

        lblDistributorAdmin1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblDistributorAdmin1.setForeground(new java.awt.Color(243, 233, 220));
        lblDistributorAdmin1.setText("DISTRIBUTOR MANAGER");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblDistributorAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDistributorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                        .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistributorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDistributorAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        jTabbedPane1.setBackground(new java.awt.Color(137, 87, 55));
        jTabbedPane1.setForeground(new java.awt.Color(243, 233, 220));

        ViewOrdersPanel.setBackground(new java.awt.Color(137, 87, 55));

        txtSearch.setText("Search: ");

        btnOrder.setText("Order Overview");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        tblOrderOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Order Date", "Supplier", "Order Status", "Shipping Partner"
            }
        ));
        tblOrderOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderOverviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrderOverview);

        lblManufac.setForeground(new java.awt.Color(243, 233, 220));
        lblManufac.setText("Manufacturer");

        lblOrderID.setForeground(new java.awt.Color(243, 233, 220));
        lblOrderID.setText("Supplier Name");

        jLabel1.setForeground(new java.awt.Color(243, 233, 220));
        jLabel1.setText("XXX");

        lblStatus.setForeground(new java.awt.Color(243, 233, 220));
        lblStatus.setText("Status");

        lblSupplierName.setForeground(new java.awt.Color(243, 233, 220));
        lblSupplierName.setText("XXX");

        lblSts.setForeground(new java.awt.Color(209, 209, 250));
        lblSts.setText("XXX");

        btnAssignTransportNow.setText("Assign Transport Services Now");
        btnAssignTransportNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTransportNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewOrdersPanelLayout = new javax.swing.GroupLayout(ViewOrdersPanel);
        ViewOrdersPanel.setLayout(ViewOrdersPanelLayout);
        ViewOrdersPanelLayout.setHorizontalGroup(
            ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOrder)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAssignTransportNow)
                            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManufac)
                                    .addComponent(lblOrderID)
                                    .addComponent(lblStatus))
                                .addGap(37, 37, 37)
                                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSts, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        ViewOrdersPanelLayout.setVerticalGroup(
            ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewOrdersPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufac)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(lblSupplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblSts))
                .addGap(18, 18, 18)
                .addComponent(btnAssignTransportNow)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Order Overview", ViewOrdersPanel);

        TransportManagementPanel.setBackground(new java.awt.Color(137, 87, 55));

        btnOrderrOverview.setText("Order Overview");
        btnOrderrOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderrOverviewActionPerformed(evt);
            }
        });

        tblOrderrOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Manufacturer", "Order Date", "Status"
            }
        ));
        tblOrderrOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderrOverviewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrderrOverview);

        btnTransportationOverview.setText("Transportation Overview");
        btnTransportationOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportationOverviewActionPerformed(evt);
            }
        });

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tblTransportation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transporter ID", "Transporter Name", "Vehicles in Use"
            }
        ));
        tblTransportation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransportationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTransportation);

        btnAssignTransport.setText("Assign Transportation");
        btnAssignTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTransportActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransportManagementPanelLayout = new javax.swing.GroupLayout(TransportManagementPanel);
        TransportManagementPanel.setLayout(TransportManagementPanelLayout);
        TransportManagementPanelLayout.setHorizontalGroup(
            TransportManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransportManagementPanelLayout.createSequentialGroup()
                .addGroup(TransportManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransportManagementPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(TransportManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTransportationOverview)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
                            .addComponent(btnOrderrOverview)
                            .addComponent(jScrollPane3)))
                    .addGroup(TransportManagementPanelLayout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(btnAssignTransport))
                    .addGroup(TransportManagementPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        TransportManagementPanelLayout.setVerticalGroup(
            TransportManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransportManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnOrderrOverview)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnTransportationOverview)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssignTransport)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transportation Management", TransportManagementPanel);

        ShipmentOverviewPanel.setBackground(new java.awt.Color(137, 87, 55));

        jTabbedPane2.setBackground(new java.awt.Color(137, 87, 55));
        jTabbedPane2.setForeground(new java.awt.Color(243, 233, 220));

        StockOverviewPane.setBackground(new java.awt.Color(137, 87, 55));

        txtSearchh.setText("SEARCH: ");

        btnTrackShipment.setText("Track Shipment");
        btnTrackShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackShipmentActionPerformed(evt);
            }
        });

        tblTrackShipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transport ID", "Order ID", "Status"
            }
        ));
        tblTrackShipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrackShipmentMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTrackShipment);

        btnBackk.setText("BACK");

        javax.swing.GroupLayout StockOverviewPaneLayout = new javax.swing.GroupLayout(StockOverviewPane);
        StockOverviewPane.setLayout(StockOverviewPaneLayout);
        StockOverviewPaneLayout.setHorizontalGroup(
            StockOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockOverviewPaneLayout.createSequentialGroup()
                .addGroup(StockOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockOverviewPaneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(StockOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                            .addComponent(btnTrackShipment)
                            .addComponent(txtSearchh)))
                    .addGroup(StockOverviewPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackk)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        StockOverviewPaneLayout.setVerticalGroup(
            StockOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockOverviewPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBackk)
                .addGap(26, 26, 26)
                .addComponent(txtSearchh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnTrackShipment)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Stock Overview", StockOverviewPane);

        ManageStocksPane.setBackground(new java.awt.Color(137, 87, 55));

        txtManageSearch.setText("SEARCH:");
        txtManageSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtManageSearchMouseClicked(evt);
            }
        });
        txtManageSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManageSearchKeyReleased(evt);
            }
        });

        btnMedicationOverview.setText("Medication Overview");
        btnMedicationOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicationOverviewActionPerformed(evt);
            }
        });

        jLabel4.setText("Add Inventory");

        jLabel5.setText("Product ID");

        lblProductID.setText("XXX");

        jLabel7.setText("Product Name");

        lblProductName.setText("xxxx");

        jLabel9.setText("Unites Available");

        jLabel10.setText("Purchase Price");

        jLabel11.setText("Selling Price");

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });

        txtCostPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostPriceKeyTyped(evt);
            }
        });

        txtSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellingPriceActionPerformed(evt);
            }
        });
        txtSellingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSellingPriceKeyTyped(evt);
            }
        });

        btnAddInventory.setText("Add Inventory");
        btnAddInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInventoryActionPerformed(evt);
            }
        });

        btnUpdateInventory.setText("Update Inventory");
        btnUpdateInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInventoryActionPerformed(evt);
            }
        });

        btnDeleteInventory.setText("Delete Inventory");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQty)
                                    .addComponent(txtCostPrice)
                                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(lblProductID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddInventory)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdateInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteInventory)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblProductID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblProductName))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInventory)
                    .addComponent(btnUpdateInventory)
                    .addComponent(btnDeleteInventory))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tblMedicationOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Product Name"
            }
        ));
        jScrollPane5.setViewportView(tblMedicationOverview);

        btnViewStock.setText("VIEW STOCK");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });

        tblViewStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Unites Available", "Purchase Price", "Selling Price"
            }
        ));
        tblViewStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewStockMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblViewStock);

        javax.swing.GroupLayout ManageStocksPaneLayout = new javax.swing.GroupLayout(ManageStocksPane);
        ManageStocksPane.setLayout(ManageStocksPaneLayout);
        ManageStocksPaneLayout.setHorizontalGroup(
            ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(btnViewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedicationOverview)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                        .addGroup(ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManageSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 210, Short.MAX_VALUE))))
        );
        ManageStocksPaneLayout.setVerticalGroup(
            ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtManageSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(ManageStocksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ManageStocksPaneLayout.createSequentialGroup()
                        .addComponent(btnMedicationOverview)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewStock)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Manage Stocks", ManageStocksPane);

        javax.swing.GroupLayout ShipmentOverviewPanelLayout = new javax.swing.GroupLayout(ShipmentOverviewPanel);
        ShipmentOverviewPanel.setLayout(ShipmentOverviewPanelLayout);
        ShipmentOverviewPanelLayout.setHorizontalGroup(
            ShipmentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShipmentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        ShipmentOverviewPanelLayout.setVerticalGroup(
            ShipmentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShipmentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shipment Overview", ShipmentOverviewPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(50, 50, 50))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTrackShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackShipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrackShipmentActionPerformed

    private void txtSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSellingPriceActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblOrderOverview);
        DefaultTableModel manuOrderTable= (DefaultTableModel)tblOrderOverview.getModel();
        manuOrderTable.setRowCount(0);
        try
        {
            ResultSet rs = Distributor_Manager.getShipments(distributorId);

            while(rs.next())
            {
                int orderId = rs.getInt("order_id");
                String orderDate = rs.getString("order_date");
                String distributorName = rs.getString("distributor_name");
                int transporterId = rs.getInt("transporter_id");
                String transporterName = rs.getString("transporter_name");
                String OrderStatus = rs.getString("order_status");

                Object[] rowData = new Object[5];

                rowData[0] = orderId;
                rowData[1] = orderDate;
                rowData[2] = distributorName;
                rowData[3] = OrderStatus;
                rowData[4] = transporterName;
                manuOrderTable.addRow(rowData);

            }
        }

        catch(Exception e){
            System.out.print(e);
        }

    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnAssignTransportNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTransportNowActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnAssignTransportNowActionPerformed

    private void btnOrderrOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderrOverviewActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblOrderrOverview);
        DefaultTableModel manuOrderTable1= (DefaultTableModel)tblOrderrOverview.getModel();
        manuOrderTable1.setRowCount(0);

        try
        {
            ResultSet rs = Distributor_Manager.getShipments(distributorId);

            while(rs.next())
            {
                int orderId = rs.getInt("order_id");
                String orderDate = rs.getString("order_date");
                String manuName = rs.getString("distributor_name");
                int transporterId = rs.getInt("transporter_id");
                String OrderStatus = rs.getString("order_status");

                //float totalPrice = quantity*unitPrice;

                Object[] rowData = new Object[4];

                rowData[0] = orderId;
                rowData[1] = manuName;
                rowData[2] = orderDate;
                rowData[3] = OrderStatus;

                manuOrderTable1.addRow(rowData);

            }
        }

        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnOrderrOverviewActionPerformed

    private void tblOrderrOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderrOverviewMouseClicked
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblOrderrOverview);
        int selectedIndx = tblOrderrOverview.getSelectedRow();
        DefaultTableModel tblOrderOverview= (DefaultTableModel)tblOrderrOverview.getModel();
        

        selectedOrderId = Integer.parseInt(tblOrderOverview.getValueAt(selectedIndx,0).toString());
    }//GEN-LAST:event_tblOrderrOverviewMouseClicked

    private void btnTransportationOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportationOverviewActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblTransportation);
        DefaultTableModel disOrderTable1= (DefaultTableModel)tblTransportation.getModel();
        disOrderTable1.setRowCount(0);

        try
        {
            //QUERY TO FETCH DISTRIBUTOR DETAILS
            ResultSet rs = Distributor_Manager.getTransportationVehicles();

            while(rs.next())
            {
                int tranId = rs.getInt("transporter_id");
                String transName = rs.getString("transporter_name");
                int vcount = rs.getInt("vehicle_count");

                Object[] rowData = new Object[3];

                rowData[0] = tranId;
                rowData[1] = transName;
                rowData[2] = vcount;

                disOrderTable1.addRow(rowData);

            }
        }

        catch(Exception e){
            System.out.print(e);
        }

    }//GEN-LAST:event_btnTransportationOverviewActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void tblTransportationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransportationMouseClicked
        // TODO add your handling code here:
        try
        {UI_DesignFunctions.AlignTableContents(tblTransportation);
        int selectedIndx = tblTransportation.getSelectedRow();
        DefaultTableModel DisOrderTable= (DefaultTableModel)tblTransportation.getModel();

        if(selectedIndx<0){
            JOptionPane.showMessageDialog(this,"Please assign a Distributor");
        }
        transporterId = Integer.parseInt(DisOrderTable.getValueAt(selectedIndx,0).toString());
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblTransportationMouseClicked

    private void btnAssignTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTransportActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println(selectedOrderId+transporterId);
            Distributor_Manager.assignTransporter(selectedOrderId, transporterId);
            JOptionPane.showMessageDialog(this,"Distributor Assigned for the ORDER ID "+selectedOrderId+"Successfully");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAssignTransportActionPerformed

    private void tblTrackShipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrackShipmentMouseClicked
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblTrackShipment);
        int selectedIndx = tblTrackShipment.getSelectedRow();
        DefaultTableModel ManufactOrderTable= (DefaultTableModel)tblTrackShipment.getModel();

        if(selectedIndx<0){
            JOptionPane.showMessageDialog(this,"Please Select a Drug to add");
        }
        int drugId = Integer.parseInt(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        String drugName = ManufactOrderTable.getValueAt(selectedIndx,1).toString();
        //String quantity = ManufactOrderTable.getValueAt(selectedIndx,2).toString();

        lblProductID.setText(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        lblProductName.setText(drugName);
    }//GEN-LAST:event_tblTrackShipmentMouseClicked

    private void txtManageSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtManageSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManageSearchMouseClicked

    private void txtManageSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManageSearchKeyReleased
        // TODO add your handling code here:
        String keyword = txtManageSearch.getText();
        UI_DesignFunctions.searchEmployeeDetails(keyword, tblMedicationOverview);
        UI_DesignFunctions.searchEmployeeDetails(keyword, tblViewStock);
    }//GEN-LAST:event_txtManageSearchKeyReleased

    private void btnMedicationOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicationOverviewActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblMedicationOverview);
        DefaultTableModel manuDrugTable= (DefaultTableModel)tblMedicationOverview.getModel();
        manuDrugTable.setRowCount(0);
    }//GEN-LAST:event_btnMedicationOverviewActionPerformed

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        // TODO add your handling code here:
        char c = evt. getKeyChar ();
        if (!Character.isDigit (c)){
            JOptionPane.showMessageDialog(null, "Please enter Valid Quantity!", "Error", JOptionPane.ERROR_MESSAGE);
            evt. consume ();
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtCostPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostPriceKeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Cost-Price", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        } else {
            // If the character is not a letter, try to parse it as a double
            try {
                Double.parseDouble(txtCostPrice.getText() + evt.getKeyChar());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please Enter Valid Cost-Price", "Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCostPriceKeyTyped

    private void txtSellingPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingPriceKeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Please enter valid Selling Price", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        } else {
            // If the character is not a letter, try to parse it as a double
            try {
                Double.parseDouble(txtSellingPrice.getText() + evt.getKeyChar());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter Valid Selling Price", "Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtSellingPriceKeyTyped

    private void btnAddInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInventoryActionPerformed
        // TODO add your handling code here:
        if (txtQty.getText().isEmpty() || txtCostPrice.getText().isEmpty() || txtSellingPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }else{

        }
    }//GEN-LAST:event_btnAddInventoryActionPerformed

    private void btnUpdateInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInventoryActionPerformed
        // TODO add your handling code here:
        int drugId = Integer.valueOf(lblProductID.getText());
        String drugName = lblProductName.getText();
        int quantity = Integer.parseInt(txtQty.getText());
        float cp = Float.valueOf(txtCostPrice.getText());
        float sp = Float.valueOf(txtSellingPrice.getText());
    }//GEN-LAST:event_btnUpdateInventoryActionPerformed

    private void tblViewStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewStockMouseClicked
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblViewStock);
        int selectedIndx = tblViewStock.getSelectedRow();
        DefaultTableModel ManufactOrderTable= (DefaultTableModel)tblViewStock.getModel();

        if(selectedIndx<0){
            JOptionPane.showMessageDialog(this,"Please Select a Drug to add");
        }
        int drugId = Integer.parseInt(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        String drugName = ManufactOrderTable.getValueAt(selectedIndx,1).toString();

        //String quantity = ManufactOrderTable.getValueAt(selectedIndx,2).toString();

        lblProductID.setText(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        lblProductName.setText(drugName);
        txtQty.setText(ManufactOrderTable.getValueAt(selectedIndx,2).toString());
        txtCostPrice.setText(ManufactOrderTable.getValueAt(selectedIndx,3).toString());
        txtSellingPrice.setText(ManufactOrderTable.getValueAt(selectedIndx,4).toString());
    }//GEN-LAST:event_tblViewStockMouseClicked

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblViewStock);
        DefaultTableModel manuDrugTable= (DefaultTableModel)tblViewStock.getModel();
        manuDrugTable.setRowCount(0);
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void tblOrderOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderOverviewMouseClicked
        // TODO add your handling code here:
        int selectedIndex = tblOrderOverview.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel) tblOrderOverview.getModel();
        jLabel1.setText(tbl.getValueAt(selectedIndex,0).toString());
        lblSupplierName.setText(tbl.getValueAt(selectedIndex,2).toString());
        lblSts.setText(tbl.getValueAt(selectedIndex, 3).toString());
    }//GEN-LAST:event_tblOrderOverviewMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        UI_Manager.init();
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JPanel ManageStocksPane;
    private javax.swing.JPanel ShipmentOverviewPanel;
    private javax.swing.JPanel StockOverviewPane;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TransportManagementPanel;
    private javax.swing.JPanel ViewOrdersPanel;
    private javax.swing.JButton btnAddInventory;
    private javax.swing.JButton btnAssignTransport;
    private javax.swing.JButton btnAssignTransportNow;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackk;
    private javax.swing.JButton btnDeleteInventory;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMedicationOverview;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnOrderrOverview;
    private javax.swing.JButton btnTrackShipment;
    private javax.swing.JButton btnTransportationOverview;
    private javax.swing.JButton btnUpdateInventory;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDistributorAdmin;
    private javax.swing.JLabel lblDistributorAdmin1;
    private javax.swing.JLabel lblManufac;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSts;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JTable tblMedicationOverview;
    private javax.swing.JTable tblOrderOverview;
    private javax.swing.JTable tblOrderrOverview;
    private javax.swing.JTable tblTrackShipment;
    private javax.swing.JTable tblTransportation;
    private javax.swing.JTable tblViewStock;
    private javax.swing.JTextField txtCostPrice;
    private javax.swing.JTextField txtManageSearch;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchh;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
