/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.manufacturer;

import database.Manufacture_Manager;
import database.PharmacyManager;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import ui.manager.UI_DesignFunctions;
import ui.manager.UI_Manager;
import java.sql.*;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author KAILASH
 */
public class ManufacturerAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerAdminJPanel
     */
    String username;
    int manufacturerId;
    public ManufacturerAdminJPanel(String username, int manufacturerId) {
        initComponents();
        lblpharmacyAdminName.setText(username);
        this.username = username;
        this.manufacturerId = manufacturerId;
        UI_DesignFunctions.SetButtonBgGreen(btnApproveOrdReq);
        UI_DesignFunctions.SetButtonBgRed(btnDeclineOrdReq);
        btnAssignDistributorToOrder.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        lblpharmacyAdminName = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        bottomTabbedPane = new javax.swing.JTabbedPane();
        manageOrdersJPanel = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        txtSearchEmployeeKeywordd = new javax.swing.JTextField();
        btnViewOrders = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufacOrders = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManufacOrderItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnApproveOrdReq = new javax.swing.JButton();
        btnDeclineOrdReq = new javax.swing.JButton();
        btnAssignDistributorToOrder = new javax.swing.JButton();
        manageOrderDistributionJPanel = new javax.swing.JPanel();
        btnViewProcessedOrders = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        manufacOrderTableDup = new javax.swing.JTable();
        btnViewDistributors = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDistributor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPharmaName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblExpDelDate = new javax.swing.JLabel();
        lblDistriID = new javax.swing.JLabel();
        lblDistriName = new javax.swing.JLabel();
        lblAssignedOnDate = new javax.swing.JLabel();
        btnGenerateReceipt = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        printArea = new javax.swing.JTextArea();
        manageInventoryJPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jTextField32 = new javax.swing.JTextField();
        btnViewStock = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        manufacturerDrugTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jTextFieldKeyMan = new javax.swing.JTextField();
        btnViewDrugList = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblmanufacturerDrug = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        tblmanufacturerDrugTbl2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnViewStockList = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldSp = new javax.swing.JTextField();
        jLabelManDrugId = new javax.swing.JLabel();
        jLabelManDrugName = new javax.swing.JLabel();
        btnAddStock = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        btnDeleteStock = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1005, 630));

        jPanel1.setBackground(new java.awt.Color(137, 87, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(137, 87, 55));

        lblpharmacyAdminName.setBackground(new java.awt.Color(137, 87, 55));
        lblpharmacyAdminName.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lblpharmacyAdminName.setForeground(new java.awt.Color(243, 233, 220));

        lblWelcome.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(243, 233, 220));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("WELCOME");

        jButton18.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton18.setText("LOGIN PAGE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton15.setText("Close");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(lblpharmacyAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblpharmacyAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWelcome))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1000, 70));

        bottomTabbedPane.setBackground(new java.awt.Color(137, 87, 55));
        bottomTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bottomTabbedPane.setForeground(new java.awt.Color(243, 233, 220));
        bottomTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        manageOrdersJPanel.setBackground(new java.awt.Color(137, 87, 55));
        manageOrdersJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(137, 87, 55));
        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By Employee Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cascadia Mono", 1, 12))); // NOI18N
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchEmployeeKeywordd.setText("Enter Employee Details");
        txtSearchEmployeeKeywordd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEmployeeKeyworddActionPerformed(evt);
            }
        });
        txtSearchEmployeeKeywordd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchEmployeeKeyworddKeyReleased(evt);
            }
        });
        jPanel34.add(txtSearchEmployeeKeywordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 17, 453, 39));

        manageOrdersJPanel.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 960, 70));

        btnViewOrders.setText("View Orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });
        manageOrdersJPanel.add(btnViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 180, -1));

        tblManufacOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Total Order Quantity", "Pharmacy Name", "Distributor Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManufacOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManufacOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblManufacOrders);

        manageOrdersJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 900, 110));

        tblManufacOrderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Drug ID", "Drug Name", "Quantity", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblManufacOrderItems);

        manageOrdersJPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 900, 120));

        jLabel1.setForeground(new java.awt.Color(243, 233, 220));
        jLabel1.setText("CUSTOMER");
        manageOrdersJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        lblCustomer.setForeground(new java.awt.Color(243, 233, 220));
        lblCustomer.setText("XXX");
        manageOrdersJPanel.add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel7.setForeground(new java.awt.Color(243, 233, 220));
        jLabel7.setText("ORDER ID");
        manageOrdersJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        lblOrderId.setForeground(new java.awt.Color(243, 233, 220));
        lblOrderId.setText("XXX");
        manageOrdersJPanel.add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel5.setForeground(new java.awt.Color(243, 233, 220));
        jLabel5.setText("STATUS");
        manageOrdersJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 51, 0));
        lblStatus.setText("XXX");
        manageOrdersJPanel.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        btnApproveOrdReq.setText("Approve Order Request");
        btnApproveOrdReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveOrdReqActionPerformed(evt);
            }
        });
        manageOrdersJPanel.add(btnApproveOrdReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, 30));

        btnDeclineOrdReq.setText("Decline Order Request");
        btnDeclineOrdReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineOrdReqActionPerformed(evt);
            }
        });
        manageOrdersJPanel.add(btnDeclineOrdReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, 30));

        btnAssignDistributorToOrder.setText("Assign Distributor to Order");
        btnAssignDistributorToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDistributorToOrderActionPerformed(evt);
            }
        });
        manageOrdersJPanel.add(btnAssignDistributorToOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, 30));

        bottomTabbedPane.addTab("Check Orders", manageOrdersJPanel);

        manageOrderDistributionJPanel.setBackground(new java.awt.Color(137, 87, 55));
        manageOrderDistributionJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewProcessedOrders.setText("View Processed Orders");
        btnViewProcessedOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProcessedOrdersActionPerformed(evt);
            }
        });
        manageOrderDistributionJPanel.add(btnViewProcessedOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 30));

        manufacOrderTableDup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Pharma ID", "Pharma Name", "Order Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manufacOrderTableDup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manufacOrderTableDupMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(manufacOrderTableDup);

        manageOrderDistributionJPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 160));

        btnViewDistributors.setText("View Distributors");
        btnViewDistributors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDistributorsActionPerformed(evt);
            }
        });
        manageOrderDistributionJPanel.add(btnViewDistributors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 30));

        tblDistributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Distributor Name", "Distributor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDistributorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDistributor);

        manageOrderDistributionJPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 340, 140));

        jLabel2.setForeground(new java.awt.Color(243, 233, 220));
        jLabel2.setText("Click Here to assign Order to Distributor");
        manageOrderDistributionJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 240, -1));

        jButton2.setText("Assign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        manageOrderDistributionJPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 30));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        manageOrderDistributionJPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Pharma Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        lblPharmaName.setText("X");
        jPanel2.add(lblPharmaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 170, -1));

        jLabel6.setText("Expected Delivery Date:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, -1));

        lblOrderID.setText("X");
        jPanel2.add(lblOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 110));

        jLabel8.setText("Order ID:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel9.setText("Distributor ID:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        jLabel10.setText("Distributor Name:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        jLabel11.setText("Assigned ON:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, -1));

        lblExpDelDate.setText("X");
        jPanel2.add(lblExpDelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, -1));

        lblDistriID.setText("X");
        jPanel2.add(lblDistriID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, -1));

        lblDistriName.setText("X");
        jPanel2.add(lblDistriName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, -1));

        lblAssignedOnDate.setText("X");
        jPanel2.add(lblAssignedOnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, -1));

        btnGenerateReceipt.setText("Generate Assignment Receipt");
        btnGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReceiptActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 50));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-50.png"))); // NOI18N
        btnPrint.setBorder(null);
        btnPrint.setBorderPainted(false);
        btnPrint.setContentAreaFilled(false);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setOpaque(true);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 60, 60));

        jLabel18.setText("Click here to Print the Receipt:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 170, 30));

        manageOrderDistributionJPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 290, 450));

        printArea.setColumns(20);
        printArea.setRows(5);
        jScrollPane6.setViewportView(printArea);

        manageOrderDistributionJPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 310, 450));

        bottomTabbedPane.addTab("Manage Order Distribution", manageOrderDistributionJPanel);

        jTabbedPane1.setBackground(new java.awt.Color(137, 87, 55));
        jTabbedPane1.setForeground(new java.awt.Color(243, 233, 220));

        jPanel3.setBackground(new java.awt.Color(137, 87, 55));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(137, 87, 55));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH BY"));

        jTextField32.setText("SEARCH BY KEYWORD");
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel3.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, -1, 78));

        btnViewStock.setText("VIEW STOCK");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        manufacturerDrugTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        manufacturerDrugTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DRUG ID", "DRUG NAME", "QUANTITY", "SELLING PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        manufacturerDrugTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manufacturerDrugTable1MouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(manufacturerDrugTable1);

        jPanel3.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 940, 260));

        jTabbedPane1.addTab("View Available Stock", jPanel3);

        jPanel4.setBackground(new java.awt.Color(137, 87, 55));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBackground(new java.awt.Color(137, 87, 55));
        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH DRUGS"));

        jTextFieldKeyMan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldKeyManKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldKeyMan, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addComponent(jTextFieldKeyMan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 955, -1));

        btnViewDrugList.setText("View List");
        btnViewDrugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugListActionPerformed(evt);
            }
        });
        jPanel4.add(btnViewDrugList, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(243, 233, 220));
        jLabel4.setText("Click here to View Drug List");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 20));

        tblmanufacturerDrug.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        tblmanufacturerDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "CROCIN"},
                { new Integer(2), "PARACETAMOL"}
            },
            new String [] {
                "DRUG ID", "DRUG NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblmanufacturerDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanufacturerDrugMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblmanufacturerDrugMouseEntered(evt);
            }
        });
        jScrollPane13.setViewportView(tblmanufacturerDrug);

        jPanel4.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 130));

        tblmanufacturerDrugTbl2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        tblmanufacturerDrugTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "CROCIN",  new Integer(5),  new Float(23.0), "45"},
                { new Integer(2), "PARA",  new Integer(7),  new Float(33.0), "44"}
            },
            new String [] {
                "DRUG ID", "DRUG NAME", "QUANTITY", "COST PRICE", "SELLING PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblmanufacturerDrugTbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanufacturerDrugTbl2MouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(tblmanufacturerDrugTbl2);

        jPanel4.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 140));

        jLabel12.setForeground(new java.awt.Color(243, 233, 220));
        jLabel12.setText("Click here to View Stock List");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 20));

        btnViewStockList.setText("View List");
        btnViewStockList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockListActionPerformed(evt);
            }
        });
        jPanel4.add(btnViewStockList, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jPanel5.setBackground(new java.awt.Color(137, 87, 55));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("ADD STOCK"));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel13.setForeground(new java.awt.Color(243, 233, 220));
        jLabel13.setText("DRUG ID");

        jLabel14.setForeground(new java.awt.Color(243, 233, 220));
        jLabel14.setText("DRUG NAME");

        jLabel15.setForeground(new java.awt.Color(243, 233, 220));
        jLabel15.setText("QUANTITY");

        jLabel16.setForeground(new java.awt.Color(243, 233, 220));
        jLabel16.setText("COST PRICE");

        jLabel17.setForeground(new java.awt.Color(243, 233, 220));
        jLabel17.setText("SELLING PRICE");

        jTextFieldQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantityKeyTyped(evt);
            }
        });

        jTextFieldCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCpKeyTyped(evt);
            }
        });

        jTextFieldSp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSpKeyTyped(evt);
            }
        });

        jLabelManDrugId.setForeground(new java.awt.Color(243, 233, 220));
        jLabelManDrugId.setText("XXX");

        jLabelManDrugName.setForeground(new java.awt.Color(243, 233, 220));
        jLabelManDrugName.setText("XXX");

        btnAddStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-stock-48.png"))); // NOI18N
        btnAddStock.setBorderPainted(false);
        btnAddStock.setContentAreaFilled(false);
        btnAddStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        btnUpdateStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-stockUpdate-50.png"))); // NOI18N
        btnUpdateStock.setBorder(null);
        btnUpdateStock.setBorderPainted(false);
        btnUpdateStock.setContentAreaFilled(false);
        btnUpdateStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        btnDeleteStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-48.png"))); // NOI18N
        btnDeleteStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteStock.setBorderPainted(false);
        btnDeleteStock.setContentAreaFilled(false);
        btnDeleteStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStockActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(243, 233, 220));
        jLabel19.setText("Add Stock");

        jLabel20.setForeground(new java.awt.Color(243, 233, 220));
        jLabel20.setText("Update Stock");

        jLabel21.setForeground(new java.awt.Color(243, 233, 220));
        jLabel21.setText("Delete Stock");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelManDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelManDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelManDrugId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelManDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 360));

        jTabbedPane1.addTab("Manage Available Stock", jPanel4);

        javax.swing.GroupLayout manageInventoryJPanelLayout = new javax.swing.GroupLayout(manageInventoryJPanel);
        manageInventoryJPanel.setLayout(manageInventoryJPanelLayout);
        manageInventoryJPanelLayout.setHorizontalGroup(
            manageInventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        manageInventoryJPanelLayout.setVerticalGroup(
            manageInventoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        bottomTabbedPane.addTab("Manage Inventory", manageInventoryJPanel);

        jPanel1.add(bottomTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 980, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        UI_Manager.init();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed
/*
    private vtxtSearchEmployeeKeywordwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeywordKeyReleased
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeywordKeyReleased
*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        UI_DesignFunctions.AlignTableContents(manufacturerDrugTable1);
        DefaultTableModel manuDrugTable= (DefaultTableModel)manufacturerDrugTable1.getModel();
        manuDrugTable.setRowCount(0);

        try
        {
            ResultSet rs = Manufacture_Manager.fetchStock(manufacturerId);

            while(rs.next())
            {
                int drugId = rs.getInt("drug_id");
                String drugName = rs.getString("drug_name");
                int quantity = rs.getInt("quantity");
                Float unitPrice = rs.getFloat("selling_price");
                Object[] rowData = new Object[4];
                rowData[0] = drugId;
                rowData[1] = drugName;
                rowData[2] = quantity;
                rowData[3] = unitPrice;
                manuDrugTable.addRow(rowData);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        } 
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void manufacturerDrugTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manufacturerDrugTable1MouseClicked

    }//GEN-LAST:event_manufacturerDrugTable1MouseClicked

    private void jTextFieldKeyManKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyManKeyReleased
        String keyword = jTextFieldKeyMan.getText();
        UI_DesignFunctions.searchEmployeeDetails(keyword, tblmanufacturerDrug);
        UI_DesignFunctions.searchEmployeeDetails(keyword, tblmanufacturerDrugTbl2);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeyManKeyReleased

    private void tblmanufacturerDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanufacturerDrugMouseClicked
        UI_DesignFunctions.AlignTableContents(tblmanufacturerDrug);
        int selectedIndx = tblmanufacturerDrug.getSelectedRow();
        DefaultTableModel tblManufactOrder= (DefaultTableModel)tblmanufacturerDrug.getModel();

        if(selectedIndx<0){
            JOptionPane.showMessageDialog(this,"Please Select a Drug to add");
        }
        int drugId = Integer.parseInt(tblManufactOrder.getValueAt(selectedIndx,0).toString());
        String drugName = tblManufactOrder.getValueAt(selectedIndx,1).toString();
        // Adding Label
        jLabelManDrugId.setText(tblManufactOrder.getValueAt(selectedIndx,0).toString());
        jLabelManDrugName.setText(drugName);

        // TODO add your handling code here:
    }//GEN-LAST:event_tblmanufacturerDrugMouseClicked

    private void tblmanufacturerDrugMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanufacturerDrugMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmanufacturerDrugMouseEntered

    private void tblmanufacturerDrugTbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanufacturerDrugTbl2MouseClicked
        UI_DesignFunctions.AlignTableContents(tblmanufacturerDrugTbl2);
        int selectedIndx = tblmanufacturerDrugTbl2.getSelectedRow();
        DefaultTableModel ManufactOrderTable= (DefaultTableModel) tblmanufacturerDrugTbl2.getModel();

        if(selectedIndx<0){
            JOptionPane.showMessageDialog(this,"Please Select a Drug to add");
        }
        int drugId = Integer.parseInt(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        String drugName = ManufactOrderTable.getValueAt(selectedIndx,1).toString();


        jLabelManDrugId.setText(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        jLabelManDrugName.setText(drugName);
        jTextFieldQuantity.setText(ManufactOrderTable.getValueAt(selectedIndx,2).toString());
        jTextFieldCp.setText(ManufactOrderTable.getValueAt(selectedIndx,3).toString());
        jTextFieldSp.setText(ManufactOrderTable.getValueAt(selectedIndx,4).toString());
    }//GEN-LAST:event_tblmanufacturerDrugTbl2MouseClicked

    private void jTextFieldQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantityKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            JOptionPane.showMessageDialog(null, "Please enter Valid Quantity!", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldQuantityKeyTyped

    private void jTextFieldCpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCpKeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Please enter Valid Cost-Price", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        } else {
            // If the character is not a letter, try to parse it as a double
            try {
                Double.parseDouble(jTextFieldCp.getText() + evt.getKeyChar());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please Enter Valid Cost-Price", "Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }

    }//GEN-LAST:event_jTextFieldCpKeyTyped

    private void jTextFieldSpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSpKeyTyped
        // TODO add your handling code here:
        if (Character.isLetter(evt.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "Please enter valid Selling Price", "Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        } else {
            // If the character is not a letter, try to parse it as a double
            try {
                Double.valueOf(jTextFieldSp.getText() + evt.getKeyChar());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter Valid Selling Price", "Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }

    }//GEN-LAST:event_jTextFieldSpKeyTyped

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed

        String drugId = jLabelManDrugId.getText();
        String drugName = jLabelManDrugName.getText();
        String quantity = jTextFieldQuantity.getText();
        String cp = jTextFieldCp.getText();
        String sp = jTextFieldSp.getText();
        
        if (jTextFieldQuantity.getText().isEmpty() || jTextFieldCp.getText().isEmpty() || jTextFieldSp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }else{
//        
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_mgmt?zeroDateTimeBehavior=CONVERT_TO_NULL","root","password");



                String sql = "INSERT INTO pharmacy_inventory(pharmacy_id, drug_id, quantity, cost_price, selling_price)" +
                         "VALUES (?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                
                pstmt.setString(1, drugId);        
                pstmt.setString(2, drugId);
                pstmt.setString(3, quantity);
                pstmt.setString(4, cp);
                pstmt.setString(5, sp);
                int rowsInserted = pstmt.executeUpdate();
            }
            catch(Exception e)
            {
                System.out.print(e.getMessage());
            } 
        }

    }//GEN-LAST:event_btnAddStockActionPerformed

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed

        String drugId = jLabelManDrugId.getText();
        String drugName = jLabelManDrugName.getText();
        String quantity = jTextFieldQuantity.getText();
        String cp = jTextFieldCp.getText();
        String sp = jTextFieldSp.getText();
        
        
        try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_mgmt?zeroDateTimeBehavior=CONVERT_TO_NULL","root","password");



                String sql = "UPDATE pharmacy_inventory set quantity=%s and cost_price=%s and selling_price=%s where drug_id=%s";
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                
                pstmt.setString(1, quantity);        
                pstmt.setString(2, cp);
                pstmt.setString(3, sp);
                pstmt.setString(4, drugId);
//                pstmt.setString(5, );
                int rowsInserted = pstmt.executeUpdate();
            }
            catch(Exception e)
            {
                System.out.print(e.getMessage());
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void btnDeleteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStockActionPerformed
        // TODO add your handling code here:
        String drug_Id = jLabelManDrugId.getText();
        
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_mgmt?zeroDateTimeBehavior=CONVERT_TO_NULL","root","password");



                String sql = "DELETE from pharmacy_inventory where drug_id=%s";
                
                PreparedStatement pstmt = conn.prepareStatement(sql);
                
                pstmt.setString(1, drug_Id);        

//                pstmt.setString(5, );
                int rowsInserted = pstmt.executeUpdate();
            }
            catch(Exception e)
            {
                System.out.print(e.getMessage());
            } 
    }//GEN-LAST:event_btnDeleteStockActionPerformed

    private void btnViewDrugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugListActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblmanufacturerDrug);
        DefaultTableModel manuDrugTable= (DefaultTableModel)tblmanufacturerDrug.getModel();
        manuDrugTable.setRowCount(0);
   try
    {
        ResultSet rs = Manufacture_Manager.fetchAllDrugs();
        while(rs.next())
        {
            int drugId = rs.getInt("drug_id");
            String drugName = rs.getString("drug_name");
            Object[] rowData = new Object[2];
            rowData[0] = drugId;
            rowData[1] = drugName;
            manuDrugTable.addRow(rowData);    
        }
    }
    catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnViewDrugListActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
    try{
    
        UI_DesignFunctions.AlignTableContents(tblManufacOrders);
        DefaultTableModel manuOrderTable= (DefaultTableModel)tblManufacOrders.getModel();
        manuOrderTable.setRowCount(0);

        ResultSet rs = Manufacture_Manager.fetchAllOrders(manufacturerId);

        while(rs.next())
        {
            int orderId = rs.getInt("order_id");
            String orderDate = rs.getString("order_date");
            int pharmacyId = rs.getInt("pharmacy_id");
            String pharmacyName = rs.getString("pharmacy_name");
            int quantity = rs.getInt("total_items");
            String distrubutorName = rs.getString("distributor_name");
            String OrderStatus = rs.getString("order_status");

            Object[] rowData = new Object[6];

            rowData[0] = orderId;
            rowData[1] = orderDate;
            rowData[2] = quantity;
            rowData[3] = pharmacyName;
            rowData[4] = distrubutorName;
            rowData[5] = OrderStatus;      
            manuOrderTable.addRow(rowData);    
        }
    } 
    
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnViewOrdersActionPerformed

    private void tblManufacOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManufacOrdersMouseClicked
        // TODO add your handling code here:
        
        Color globalColor = new Color(227, 66, 52);
        lblStatus.setForeground(globalColor);
        UI_DesignFunctions.AlignTableContents(tblManufacOrderItems);

        int selectedIndx = tblManufacOrders.getSelectedRow();
        DefaultTableModel ManufactOrderTable= (DefaultTableModel)tblManufacOrders.getModel();

        DefaultTableModel ManufactOrderItmTable  = (DefaultTableModel)tblManufacOrderItems.getModel();
        ManufactOrderItmTable.setRowCount(0);

        if(selectedIndx<0){
        JOptionPane.showMessageDialog(this,"Please Select an Order to Review");
        }
        int orderId = Integer.parseInt(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        String pharmacyName = ManufactOrderTable.getValueAt(selectedIndx,3).toString();
        String orderStatus = ManufactOrderTable.getValueAt(selectedIndx,5).toString();

        lblOrderId.setText(ManufactOrderTable.getValueAt(selectedIndx,0).toString());
        lblCustomer.setText(pharmacyName);
        lblStatus.setText(orderStatus);

        try
        {
                ResultSet rs = Manufacture_Manager.fetchAllOrderItems(orderId);

                while(rs.next()){
                int drugId = rs.getInt("item_id");
                String drugName = rs.getString("drug_name");
                int quantity = rs.getInt("quantity");
                float unitPrice = rs.getFloat("unit_price");

                Object[] rowData = new Object[5];

                rowData[0] = orderId;
                rowData[1] = drugId;
                rowData[2] = drugName;
                rowData[3] = quantity;
                rowData[4] = unitPrice;

                ManufactOrderItmTable.addRow(rowData);
                }

        }  
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblManufacOrdersMouseClicked

    private void btnApproveOrdReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveOrdReqActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Approve the order request?", "Approve the order request?", JOptionPane.YES_NO_OPTION);
        if(response == 0)
        {
            // setting button colour to green to show order is approved
            Color globalColor = new Color(129, 211, 129);
            int orderId = Integer.parseInt(lblOrderId.getText());
            lblStatus.setText("Approved");
            String status = lblStatus.getText();
            try{
                Manufacture_Manager.updateOrder(orderId,status);
                lblStatus.setText("");
                lblStatus.setForeground(globalColor);

                DefaultTableModel tblManufacOrder= (DefaultTableModel) tblManufacOrders.getModel();
                int selectedIndx = tblManufacOrders.getSelectedRow();
                
                tblManufacOrder.setValueAt("Approve", selectedIndx, 5);
                tblManufacOrder.removeRow(selectedIndx);
                
                DefaultTableModel tblManufactOrderItm  = (DefaultTableModel) tblManufacOrderItems.getModel();
                tblManufactOrderItm.setRowCount(0);
                btnAssignDistributorToOrder.setVisible(true);
            } 
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnApproveOrdReqActionPerformed

    public void searchEmployeeDetails(String x){
        DefaultTableModel tableSearch = (DefaultTableModel)tblManufacOrders.getModel();
        TableRowSorter<DefaultTableModel> sortertableSearch = new TableRowSorter<>(tableSearch);
        tblManufacOrders.setRowSorter(sortertableSearch);
        sortertableSearch.setRowFilter(RowFilter.regexFilter("(?i)"+x));

}
    private void txtSearchEmployeeKeyworddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEmployeeKeyworddKeyReleased
        // TODO add your handling code here:
        String keyword = txtSearchEmployeeKeywordd.getText();
        searchEmployeeDetails(keyword);
        
    }//GEN-LAST:event_txtSearchEmployeeKeyworddKeyReleased

    private void txtSearchEmployeeKeyworddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmployeeKeyworddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchEmployeeKeyworddActionPerformed

    private void btnAssignDistributorToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDistributorToOrderActionPerformed
        // TODO add your handling code here:
        bottomTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnAssignDistributorToOrderActionPerformed

    private void manufacOrderTableDupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manufacOrderTableDupMouseClicked
        // TODO add your handling code here:
        try{
            UI_DesignFunctions.AlignTableContents(jTable2);
            int takenIndex = manufacOrderTableDup.getSelectedRow();
            DefaultTableModel MOT= (DefaultTableModel)manufacOrderTableDup.getModel();
            DefaultTableModel MOIT  = (DefaultTableModel)jTable2.getModel();

            MOIT.setRowCount(0);

            if(takenIndex<0){
            JOptionPane.showMessageDialog(this,"Please Select an Order to assign Distributor");
            }
            int orderId = Integer.parseInt(MOT.getValueAt(takenIndex,0).toString());
            String pharmacyName = MOT.getValueAt(takenIndex,1).toString();

            lblOrderID.setText(MOT.getValueAt(takenIndex,0).toString());
            lblPharmaName.setText(pharmacyName);

                    ResultSet rs = PharmacyManager.fetchAllOrderItems(orderId);

                    while(rs.next()){
                    String drugName = rs.getString("drug_name");
                    int quantity = rs.getInt("quantity");
                    String costPrice = rs.getString("cost_price");

                    Object[] rowData = new Object[3];


                    rowData[0] = drugName;
                    rowData[1] = quantity;
                    rowData[2] = costPrice;

                    MOIT.addRow(rowData);
                }
            }  
        catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_manufacOrderTableDupMouseClicked

    private void btnViewProcessedOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProcessedOrdersActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(manufacOrderTableDup);
        DefaultTableModel MOTD= (DefaultTableModel)manufacOrderTableDup.getModel();
        MOTD.setRowCount(0);


   try
    {
        ResultSet rs = Manufacture_Manager.fetchAllOrders(manufacturerId);

        while(rs.next())
        {
            int orderId = rs.getInt("order_id");
            int pharmacyId = rs.getInt("pharmacy_id");
            String pharmacyName = rs.getString("pharmacy_name");
            String orderDate = rs.getString("order_date");
            String OrderStatus = rs.getString("order_status");

            Object[] x = new Object[5];
            x[0] = orderId;
            x[1] = orderDate;
            x[2] = pharmacyId;
            x[3] = pharmacyName;
            x[4] = OrderStatus;
            MOTD.addRow(x);
        }
    }catch(Exception e){
        System.out.print(e);
        }
    }//GEN-LAST:event_btnViewProcessedOrdersActionPerformed

    private void btnViewDistributorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDistributorsActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblDistributor);
        DefaultTableModel disOrderTable1= (DefaultTableModel)tblDistributor.getModel();
        disOrderTable1.setRowCount(0);
        try
         {
             ResultSet rs = Manufacture_Manager.viewAllDistributors();

             while(rs.next())
             {
                 int distributorId = rs.getInt("company_id");
                  String distributorName = rs.getString("company_name");

                 Object[] x = new Object[2];

                 x[0] = distributorId;
                 x[1] = distributorName;

                 disOrderTable1.addRow(x);
             }
         }
         catch(Exception e){
             System.out.print(e);
         }

    }//GEN-LAST:event_btnViewDistributorsActionPerformed

    private void tblDistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDistributorMouseClicked
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblDistributor);
        int selectedIndex = tblDistributor.getSelectedRow();
        DefaultTableModel DistriOrderTable= (DefaultTableModel)tblDistributor.getModel();

        if(selectedIndex<0){
            JOptionPane.showMessageDialog(this,"Please assign a Distributor");
        }

        lblDistriID.setText(DistriOrderTable.getValueAt(selectedIndex,0).toString());
        lblDistriName.setText(DistriOrderTable.getValueAt(selectedIndex,1).toString());
        // getting current time using TIME/time import
        LocalDateTime date = LocalDateTime.now();
        LocalDateTime deliveryDate = date.plusDays(4); // setting expected delivery date for 4 days
        
        // Setting values to UI
        Timestamp AssignedTimestamp = Timestamp.valueOf(date);
        Timestamp expectedDelTimestamp = Timestamp.valueOf(deliveryDate);
        lblAssignedOnDate.setText(AssignedTimestamp.toString());
        lblExpDelDate.setText(expectedDelTimestamp.toString());
    }//GEN-LAST:event_tblDistributorMouseClicked

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
        // TODO add your handling code here:
        
        printArea.setText(" ************************************************************\n");

        printArea.setText(printArea.getText()+"\n ******* DISTRIBUTOR ASSIGNMENT RECEIPT *********** \n");
        printArea.setText(printArea.getText()+"\n *************************************************************** \n\n\n");
        printArea.setText(printArea.getText()+"\n *************************************************************** \n\n");
        printArea.setText(printArea.getText()+" Order Number : " + "      "+lblOrderID.getText()+"\n\n");
        printArea.setText(printArea.getText()+" Order Name : " + "      "+lblOrderID.getText()+"\n\n");

        printArea.setText(printArea.getText()+" Pharmacy Name : " + "     "+lblPharmaName.getText()+"\n\n");
        printArea.setText(printArea.getText()+"\n ***************************************************************\n\n\n");
        printArea.setText(printArea.getText()+" Distributor ID : " + "      "+lblDistriID.getText()+"\n\n");
        printArea.setText(printArea.getText()+" Distributor Name : " + "     "+lblDistriName.getText()+"\n\n");
        printArea.setText(printArea.getText()+"\n ***************************************************************\n\n\n");
        printArea.setText(printArea.getText()+" Assignemnt Date         : " + "    "+lblAssignedOnDate.getText()+"\n\n");
        printArea.setText(printArea.getText()+" Expected Delivery Date : " + " "+lblExpDelDate.getText()+"\n\n");
        printArea.setText(printArea.getText()+"\n ***************************************************************\n");
        printArea.setText(printArea.getText()+"\n ***************************************************************\n");
    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try
        {
            printArea.print();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int orderId = Integer.parseInt(lblOrderID.getText());
        int disId = Integer.parseInt(lblDistriID.getText());


        try
        {
            Manufacture_Manager.assignDistributor(orderId, disId);
            JOptionPane.showMessageDialog(this,"Distributor Assigned for the ORDER ID"+orderId+"Successfully");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeclineOrdReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineOrdReqActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Decline the order request?", "Decline the order request?", JOptionPane.YES_NO_OPTION);
        if(response == 0)
        {
            // setting button colour to red to show order is approved
            Color globalColor = new Color(255,0,0);
            int orderId = Integer.parseInt(lblOrderId.getText());
            lblStatus.setText("Declined");
            String status = lblStatus.getText();
            try{
                Manufacture_Manager.updateOrder(orderId,status);System.out.println("\n in manuadminJpanel");
                lblStatus.setText("");
                lblStatus.setForeground(globalColor);

                DefaultTableModel tblManufacOrder= (DefaultTableModel) tblManufacOrders.getModel();
                int selectedIndx = tblManufacOrders.getSelectedRow();
                
                tblManufacOrder.setValueAt("Declined", selectedIndx, 5);
                tblManufacOrder.removeRow(selectedIndx);
                
                DefaultTableModel tblManufactOrderItm  = (DefaultTableModel) tblManufacOrderItems.getModel();
                tblManufactOrderItm.setRowCount(0);
                btnAssignDistributorToOrder.setVisible(false);
            } 
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnDeclineOrdReqActionPerformed

    private void btnViewStockListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockListActionPerformed
        // TODO add your handling code here:
        UI_DesignFunctions.AlignTableContents(tblmanufacturerDrugTbl2);
        DefaultTableModel manuDrugTable= (DefaultTableModel)tblmanufacturerDrugTbl2.getModel();
        manuDrugTable.setRowCount(0);

        try
         {
         ResultSet rs = Manufacture_Manager.fetchAllPharmacyDrugs();

         while(rs.next())
         {
             int drugId = rs.getInt("pharmacy_id");
             String drugName = rs.getString("drug_id");
             int quantity = rs.getInt("quantity");
             Float cost_price = Float.parseFloat(rs.getString("cost_price"));
             Float selling_price = Float.parseFloat(rs.getString("selling_price"));


             Object[] rowData = new Object[4];

             rowData[0] = drugId;
             rowData[1] = drugId;
             rowData[2] = quantity;
             rowData[3] = cost_price;
             rowData[4] = selling_price;

             manuDrugTable.addRow(rowData);
         }
         } 

         catch(Exception e){
             System.out.print(e);
         }
    }//GEN-LAST:event_btnViewStockListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane bottomTabbedPane;
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnApproveOrdReq;
    private javax.swing.JButton btnAssignDistributorToOrder;
    private javax.swing.JButton btnDeclineOrdReq;
    private javax.swing.JButton btnDeleteStock;
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JButton btnViewDistributors;
    private javax.swing.JButton btnViewDrugList;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JButton btnViewProcessedOrders;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JButton btnViewStockList;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelManDrugId;
    private javax.swing.JLabel jLabelManDrugName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldKeyMan;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldSp;
    private javax.swing.JLabel lblAssignedOnDate;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDistriID;
    private javax.swing.JLabel lblDistriName;
    private javax.swing.JLabel lblExpDelDate;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblPharmaName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblpharmacyAdminName;
    private javax.swing.JPanel manageInventoryJPanel;
    private javax.swing.JPanel manageOrderDistributionJPanel;
    private javax.swing.JPanel manageOrdersJPanel;
    private javax.swing.JTable manufacOrderTableDup;
    private javax.swing.JTable manufacturerDrugTable1;
    private javax.swing.JTextArea printArea;
    private javax.swing.JTable tblDistributor;
    private javax.swing.JTable tblManufacOrderItems;
    private javax.swing.JTable tblManufacOrders;
    private javax.swing.JTable tblmanufacturerDrug;
    private javax.swing.JTable tblmanufacturerDrugTbl2;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtSearchEmployeeKeywordd;
    // End of variables declaration//GEN-END:variables
}
