/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pharmacy;

import database.Manufacture_Manager;
import javax.swing.table.DefaultTableModel;
import ui.manager.UI_DesignFunctions;
import java.sql.*;
import ui.manager.UI_Manager;
/**
 *
 * @author priyankasatish
 */
public class PharmacyStoreManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyStoreManagerPanel
     */
    String username;
    public PharmacyStoreManagerPanel(String user) {
        initComponents();
        this.username=user;
        System.out.println("PharmacyStoreManagerPanel user: "+user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ManageStock = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        btnViewStock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pharmacyAdminName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pharmacyLogo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(137, 87, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageStock.setBackground(new java.awt.Color(137, 87, 55));
        ManageStock.setForeground(new java.awt.Color(51, 0, 51));

        jPanel3.setBackground(new java.awt.Color(137, 87, 55));

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store Name", "Drug ID", "Quantity", "Cost Price", "Selling Price", "Store Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStock);

        btnViewStock.setText("View Stock");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(btnViewStock))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnViewStock)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        ManageStock.addTab("VIEW MEDINICINES STOCK", jPanel3);

        jPanel1.add(ManageStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 114, -1, -1));

        jPanel2.setBackground(new java.awt.Color(137, 87, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(pharmacyAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1522, 0, 250, 60));

        jLabel2.setBackground(new java.awt.Color(137, 87, 55));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("WELCOME TO PHARMACY STORE MANAGER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 19, 758, 60));
        jPanel2.add(pharmacyLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1778, 6, 101, 73));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 97, 42));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1620, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy_mgmt?zeroDateTimeBehavior=CONVERT_TO_NULL","root","password");

            Statement st = conn.createStatement();
            String sql = "SELECT ps.store_name,pi.drug_id, pi.quantity,pi.cost_price,pi.selling_price,ps.store_address FROM pharmacy_inventory pi JOIN pharmacy_store ps ON pi.pharmacy_id = ps.pharmacy_id;";

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                // Retrieve data from each column
                String studentID = rs.getString("store_name");
                String add1 = rs.getString("drug_id");
                String add2 = rs.getString("quantity");  // May be null
                String city = rs.getString("cost_price");
                String state = rs.getString("selling_price");
                String postalCode = rs.getString("store_address");

                // Create a row of data
                String tbData[] = {studentID, add1, add2, city, state, postalCode};

                // Get the table model and add the row
                DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();
                tblModel.addRow(tbData);
            }
            conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        UI_Manager.init();
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ManageStock;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pharmacyAdminName;
    private javax.swing.JLabel pharmacyLogo;
    private javax.swing.JTable tblStock;
    // End of variables declaration//GEN-END:variables
}
